database = {
        "users": [
        {"id":int, "name": str, "age": int, "isStudent": bool, "email": str, "city": str, "country": str},
        {"id": 0, "name": "Null", "age": 0, "isStudent": False, "email": "Null", "city": "Null", "country": "Null"},
        {"id": 1, "name": "Hamza Deraoui", "age": 19, "isStudent": True, "email": "hamza.deraoui@email.com", "city": "Oujda", "country": "Morocco"},
        {"id": 2, "name": "Ali Hassan", "age": 21, "isStudent": False, "email": "ali.hassan@email.com", "city": "Casablanca", "country": "Morocco"},
        {"id": 3, "name": "Sarah Johnson", "age": 23, "isStudent": True, "email": "sarah.johnson@email.com", "city": "New York", "country": "USA"},
        {"id": 4, "name": "Mohamed Benali", "age": 25, "isStudent": False, "email": "mohamed.benali@email.com", "city": "Rabat", "country": "Morocco"},
        {"id": 5, "name": "Emma Wilson", "age": 20, "isStudent": True, "email": "emma.wilson@email.com", "city": "London", "country": "UK"},
        {"id": 6, "name": "Ahmed Mansouri", "age": 28, "isStudent": False, "email": "ahmed.mansouri@email.com", "city": "Fez", "country": "Morocco"},
        {"id": 7, "name": "Lisa Chen", "age": 22, "isStudent": True, "email": "lisa.chen@email.com", "city": "Toronto", "country": "Canada"},
        {"id": 8, "name": "Omar El Amrani", "age": 24, "isStudent": False, "email": "omar.elamrani@email.com", "city": "Marrakech", "country": "Morocco"},
        {"id": 9, "name": "Maria Rodriguez", "age": 26, "isStudent": False, "email": "maria.rodriguez@email.com", "city": "Madrid", "country": "Spain"},
        {"id": 10, "name": "Youssef Alami", "age": 18, "isStudent": True, "email": "youssef.alami@email.com", "city": "Tangier", "country": "Morocco"},
        {"id": 11, "name": "Sophie Martin", "age": 27, "isStudent": False, "email": "sophie.martin@email.com", "city": "Paris", "country": "France"},
        {"id": 12, "name": "Karim Zahiri", "age": 29, "isStudent": False, "email": "karim.zahiri@email.com", "city": "Agadir", "country": "Morocco"},
        {"id": 13, "name": "Anna Kowalski", "age": 21, "isStudent": True, "email": "anna.kowalski@email.com", "city": "Warsaw", "country": "Poland"},
        {"id": 14, "name": "Rachid Bouazza", "age": 30, "isStudent": False, "email": "rachid.bouazza@email.com", "city": "Meknes", "country": "Morocco"},
        {"id": 15, "name": "James Thompson", "age": 19, "isStudent": True, "email": "james.thompson@email.com", "city": "Sydney", "country": "Australia"},
        {"id": 16, "name": "Elena Petrova", "age": 24, "isStudent": True, "email": "elena.petrova@email.com", "city": "Moscow", "country": "Russia"},
        {"id": 17, "name": "David Kim", "age": 31, "isStudent": False, "email": "david.kim@email.com", "city": "Seoul", "country": "South Korea"},
        {"id": 18, "name": "Fatima Zahra", "age": 20, "isStudent": True, "email": "fatima.zahra@email.com", "city": "Tetouan", "country": "Morocco"},
        {"id": 19, "name": "Lucas Meyer", "age": 27, "isStudent": False, "email": "lucas.meyer@email.com", "city": "Berlin", "country": "Germany"},
        {"id": 20, "name": "Olivia Brown", "age": 22, "isStudent": True, "email": "olivia.brown@email.com", "city": "Manchester", "country": "UK"},
        {"id": 21, "name": "Hassan Idrissi", "age": 26, "isStudent": False, "email": "hassan.idrissi@email.com", "city": "Kenitra", "country": "Morocco"},
        {"id": 22, "name": "Isabella Rossi", "age": 25, "isStudent": True, "email": "isabella.rossi@email.com", "city": "Rome", "country": "Italy"},
        {"id": 23, "name": "Chen Wei", "age": 30, "isStudent": False, "email": "chen.wei@email.com", "city": "Beijing", "country": "China"},
        {"id": 24, "name": "Nora Ait", "age": 19, "isStudent": True, "email": "nora.ait@email.com", "city": "Ouarzazate", "country": "Morocco"},
        {"id": 25, "name": "John Smith", "age": 28, "isStudent": False, "email": "john.smith@email.com", "city": "Los Angeles", "country": "USA"},
        {"id": 26, "name": "Amira Lahlou", "age": 21, "isStudent": True, "email": "amira.lahlou@email.com", "city": "Chefchaouen", "country": "Morocco"},
        {"id": 27, "name": "Pierre Dupont", "age": 32, "isStudent": False, "email": "pierre.dupont@email.com", "city": "Lyon", "country": "France"},
        {"id": 28, "name": "Sophia Andersson", "age": 23, "isStudent": True, "email": "sophia.andersson@email.com", "city": "Stockholm", "country": "Sweden"},
        {"id": 29, "name": "Aliyah Khan", "age": 20, "isStudent": True, "email": "aliyah.khan@email.com", "city": "Karachi", "country": "Pakistan"},
        {"id": 30, "name": "Daniel Silva", "age": 29, "isStudent": False, "email": "daniel.silva@email.com", "city": "Lisbon", "country": "Portugal"},
        {"id": 31, "name": "Mehdi Oualid", "age": 24, "isStudent": True, "email": "mehdi.oualid@email.com", "city": "Safi", "country": "Morocco"},
        {"id": 32, "name": "Emily Davis", "age": 27, "isStudent": False, "email": "emily.davis@email.com", "city": "Vancouver", "country": "Canada"},
        {"id": 33, "name": "Khalid Mouline", "age": 22, "isStudent": True, "email": "khalid.mouline@email.com", "city": "Essaouira", "country": "Morocco"},
        {"id": 34, "name": "Jessica Taylor", "age": 28, "isStudent": False, "email": "jessica.taylor@email.com", "city": "Chicago", "country": "USA"},
        {"id": 35, "name": "Mohamed Chafik", "age": 19, "isStudent": True, "email": "mohamed.chafik@email.com", "city": "El Jadida", "country": "Morocco"},
        {"id": 36, "name": "William Johnson", "age": 31, "isStudent": False, "email": "william.johnson@email.com", "city": "Houston", "country": "USA"},
        {"id": 37, "name": "Aya Benjelloun", "age": 20, "isStudent": True, "email": "aya.benjelloun@email.com", "city": "Settat", "country": "Morocco"},
        {"id": 38, "name": "Carlos Lopez", "age": 30, "isStudent": False, "email": "carlos.lopez@email.com", "city": "Barcelona", "country": "Spain"},
        {"id": 39, "name": "Hiba Amrani", "age": 23, "isStudent": True, "email": "hiba.amrani@email.com", "city": "Nador", "country": "Morocco"},
        {"id": 40, "name": "Jacob Miller", "age": 29, "isStudent": False, "email": "jacob.miller@email.com", "city": "San Francisco", "country": "USA"},
        {"id": 41, "name": "Nadia Rahmani", "age": 21, "isStudent": True, "email": "nadia.rahmani@email.com", "city": "Beni Mellal", "country": "Morocco"},
        {"id": 42, "name": "Hiroshi Tanaka", "age": 33, "isStudent": False, "email": "hiroshi.tanaka@email.com", "city": "Tokyo", "country": "Japan"},
        {"id": 43, "name": "Laura Schneider", "age": 22, "isStudent": True, "email": "laura.schneider@email.com", "city": "Munich", "country": "Germany"},
        {"id": 44, "name": "Zineb Azzouzi", "age": 20, "isStudent": True, "email": "zineb.azzouzi@email.com", "city": "Taza", "country": "Morocco"},
        {"id": 45, "name": "Benjamin Clark", "age": 28, "isStudent": False, "email": "benjamin.clark@email.com", "city": "Boston", "country": "USA"},
        {"id": 46, "name": "Amina Idrissi", "age": 19, "isStudent": True, "email": "amina.idrissi@email.com", "city": "Khemisset", "country": "Morocco"},
        {"id": 47, "name": "Fernando Garcia", "age": 27, "isStudent": False, "email": "fernando.garcia@email.com", "city": "Seville", "country": "Spain"},
        {"id": 48, "name": "Leila Ouchene", "age": 23, "isStudent": True, "email": "leila.ouchene@email.com", "city": "Dakhla", "country": "Morocco"},
        {"id": 49, "name": "Michael Brown", "age": 32, "isStudent": False, "email": "michael.brown@email.com", "city": "Philadelphia", "country": "USA"},
        {"id": 50, "name": "Yasmina El Idrissi", "age": 20, "isStudent": True, "email": "yasmina.elidrissi@email.com", "city": "Laayoune", "country": "Morocco"}
    ],
    
    "products": [
        {"id": 1, "name": "Laptop Pro X1", "price": 1299.99, "category": "Electronics", "stock": 45, "brand": "TechCorp"},
        {"id": 2, "name": "Wireless Headphones", "price": 199.99, "category": "Electronics", "stock": 120, "brand": "AudioMax"},
        {"id": 3, "name": "Coffee Maker Deluxe", "price": 89.99, "category": "Home & Kitchen", "stock": 78, "brand": "BrewMaster"},
        {"id": 4, "name": "Running Shoes", "price": 129.99, "category": "Sports", "stock": 95, "brand": "SportFlex"},
        {"id": 5, "name": "Smartphone Galaxy", "price": 899.99, "category": "Electronics", "stock": 67, "brand": "MobileWorks"},
        {"id": 6, "name": "Desk Chair Ergonomic", "price": 249.99, "category": "Furniture", "stock": 34, "brand": "ComfortSeating"},
        {"id": 7, "name": "Gaming Mouse", "price": 59.99, "category": "Electronics", "stock": 156, "brand": "GamePro"},
        {"id": 8, "name": "Yoga Mat Premium", "price": 39.99, "category": "Sports", "stock": 89, "brand": "FlexFit"},
        {"id": 9, "name": "Blender Power", "price": 149.99, "category": "Home & Kitchen", "stock": 42, "brand": "KitchenMax"},
        {"id": 10, "name": "Monitor 4K Ultra", "price": 399.99, "category": "Electronics", "stock": 28, "brand": "DisplayTech"},
        {"id": 11, "name": "Backpack Travel", "price": 79.99, "category": "Travel", "stock": 112, "brand": "AdventureGear"},
        {"id": 12, "name": "Keyboard Mechanical", "price": 119.99, "category": "Electronics", "stock": 73, "brand": "TypeMaster"},
        {"id": 13, "name": "Water Bottle Smart", "price": 34.99, "category": "Sports", "stock": 145, "brand": "HydroTech"},
        {"id": 14, "name": "Table Lamp LED", "price": 49.99, "category": "Home & Kitchen", "stock": 86, "brand": "LightWorks"},
        {"id": 15, "name": "Fitness Tracker", "price": 179.99, "category": "Electronics", "stock": 91, "brand": "HealthTech"}
    ],
    
    "orders": [
        {"id": 1, "user_id": 1, "product_id": 1, "quantity": 1, "order_date": "2024-01-15", "status": "delivered", "total": 1299.99},
        {"id": 2, "user_id": 2, "product_id": 3, "quantity": 2, "order_date": "2024-01-18", "status": "shipped", "total": 179.98},
        {"id": 3, "user_id": 3, "product_id": 2, "quantity": 1, "order_date": "2024-01-20", "status": "processing", "total": 199.99},
        {"id": 4, "user_id": 1, "product_id": 7, "quantity": 1, "order_date": "2024-01-22", "status": "delivered", "total": 59.99},
        {"id": 5, "user_id": 4, "product_id": 5, "quantity": 1, "order_date": "2024-01-25", "status": "delivered", "total": 899.99},
        {"id": 6, "user_id": 5, "product_id": 8, "quantity": 3, "order_date": "2024-01-28", "status": "shipped", "total": 119.97},
        {"id": 7, "user_id": 6, "product_id": 6, "quantity": 1, "order_date": "2024-02-01", "status": "delivered", "total": 249.99},
        {"id": 8, "user_id": 7, "product_id": 4, "quantity": 2, "order_date": "2024-02-03", "status": "processing", "total": 259.98},
        {"id": 9, "user_id": 8, "product_id": 9, "quantity": 1, "order_date": "2024-02-05", "status": "delivered", "total": 149.99},
        {"id": 10, "user_id": 9, "product_id": 10, "quantity": 1, "order_date": "2024-02-08", "status": "shipped", "total": 399.99},
        {"id": 11, "user_id": 10, "product_id": 11, "quantity": 1, "order_date": "2024-02-10", "status": "delivered", "total": 79.99},
        {"id": 12, "user_id": 11, "product_id": 12, "quantity": 1, "order_date": "2024-02-12", "status": "processing", "total": 119.99},
        {"id": 13, "user_id": 12, "product_id": 13, "quantity": 4, "order_date": "2024-02-15", "status": "delivered", "total": 139.96},
        {"id": 14, "user_id": 13, "product_id": 14, "quantity": 2, "order_date": "2024-02-18", "status": "shipped", "total": 99.98},
        {"id": 15, "user_id": 14, "product_id": 15, "quantity": 1, "order_date": "2024-02-20", "status": "delivered", "total": 179.99}
    ],
    
    "categories": [
        {"id": 1, "name": "Electronics", "description": "Computers, phones, and electronic devices"},
        {"id": 2, "name": "Home & Kitchen", "description": "Household items and kitchen appliances"},
        {"id": 3, "name": "Sports", "description": "Sports equipment and fitness gear"},
        {"id": 4, "name": "Furniture", "description": "Home and office furniture"},
        {"id": 5, "name": "Travel", "description": "Travel accessories and luggage"},
        {"id": 6, "name": "Books", "description": "Physical and digital books"},
        {"id": 7, "name": "Clothing", "description": "Apparel and accessories"},
        {"id": 8, "name": "Beauty", "description": "Cosmetics and personal care"}
    ],
    
    "reviews": [
        {"id": 1, "user_id": 1, "product_id": 1, "rating": 5, "comment": "Amazing laptop! Super fast and great for programming.", "date": "2024-01-20"},
        {"id": 2, "user_id": 2, "product_id": 3, "rating": 4, "comment": "Good coffee maker, easy to use.", "date": "2024-01-25"},
        {"id": 3, "user_id": 3, "product_id": 2, "rating": 5, "comment": "Excellent sound quality, very comfortable.", "date": "2024-01-30"},
        {"id": 4, "user_id": 4, "product_id": 5, "rating": 4, "comment": "Great phone, camera is impressive.", "date": "2024-02-01"},
        {"id": 5, "user_id": 5, "product_id": 8, "rating": 5, "comment": "Perfect yoga mat, great grip and cushioning.", "date": "2024-02-03"},
        {"id": 6, "user_id": 6, "product_id": 6, "rating": 3, "comment": "Decent chair but assembly was difficult.", "date": "2024-02-05"},
        {"id": 7, "user_id": 7, "product_id": 4, "rating": 5, "comment": "Very comfortable running shoes, great for long runs.", "date": "2024-02-08"},
        {"id": 8, "user_id": 8, "product_id": 9, "rating": 4, "comment": "Powerful blender, makes great smoothies.", "date": "2024-02-10"},
        {"id": 9, "user_id": 9, "product_id": 10, "rating": 5, "comment": "Crystal clear display, perfect for work.", "date": "2024-02-12"},
        {"id": 10, "user_id": 10, "product_id": 11, "rating": 4, "comment": "Sturdy backpack with lots of compartments.", "date": "2024-02-15"}
    ],
    
    "companies": [
        {"id": 1, "name": "TechCorp", "industry": "Technology", "employees": 5000, "founded": 2010, "headquarters": "San Francisco, USA"},
        {"id": 2, "name": "AudioMax", "industry": "Consumer Electronics", "employees": 1200, "founded": 2015, "headquarters": "Berlin, Germany"},
        {"id": 3, "name": "BrewMaster", "industry": "Home Appliances", "employees": 800, "founded": 2008, "headquarters": "Milan, Italy"},
        {"id": 4, "name": "SportFlex", "industry": "Sports Equipment", "employees": 2500, "founded": 2012, "headquarters": "Portland, USA"},
        {"id": 5, "name": "MobileWorks", "industry": "Technology", "employees": 8000, "founded": 2005, "headquarters": "Seoul, South Korea"},
        {"id": 6, "name": "ComfortSeating", "industry": "Furniture", "employees": 600, "founded": 2018, "headquarters": "Copenhagen, Denmark"},
        {"id": 7, "name": "GamePro", "industry": "Gaming Accessories", "employees": 350, "founded": 2020, "headquarters": "Tokyo, Japan"},
        {"id": 8, "name": "FlexFit", "industry": "Fitness Equipment", "employees": 450, "founded": 2016, "headquarters": "Melbourne, Australia"}
    ],
    
    "employees": [
        {"id": 1, "name": "John Smith", "position": "Software Engineer", "salary": 85000, "department": "Engineering", "company_id": 1, "hire_date": "2022-03-15"},
        {"id": 2, "name": "Marie Dubois", "position": "Product Manager", "salary": 95000, "department": "Product", "company_id": 2, "hire_date": "2021-07-22"},
        {"id": 3, "name": "Carlos Rodriguez", "position": "Designer", "salary": 70000, "department": "Design", "company_id": 3, "hire_date": "2023-01-10"},
        {"id": 4, "name": "Aisha Patel", "position": "Marketing Manager", "salary": 78000, "department": "Marketing", "company_id": 4, "hire_date": "2022-09-05"},
        {"id": 5, "name": "David Kim", "position": "Data Scientist", "salary": 105000, "department": "Analytics", "company_id": 5, "hire_date": "2021-11-18"},
        {"id": 6, "name": "Elena Petrov", "position": "HR Manager", "salary": 72000, "department": "Human Resources", "company_id": 6, "hire_date": "2023-04-12"},
        {"id": 7, "name": "Takeshi Yamamoto", "position": "Quality Assurance", "salary": 65000, "department": "QA", "company_id": 7, "hire_date": "2022-12-01"},
        {"id": 8, "name": "Rebecca Taylor", "position": "Sales Manager", "salary": 88000, "department": "Sales", "company_id": 8, "hire_date": "2021-06-30"},
        {"id": 9, "name": "Hassan Benkirane", "position": "DevOps Engineer", "salary": 92000, "department": "Engineering", "company_id": 1, "hire_date": "2023-02-14"},
        {"id": 10, "name": "Isabella Garcia", "position": "UX Designer", "salary": 76000, "department": "Design", "company_id": 2, "hire_date": "2022-08-20"}
    ],
    
    "courses": [
        {"id": 1, "name": "Computer Science", "credits": 120, "duration_years": 4, "university": "Mohammed V University", "location": "Rabat"},
        {"id": 2, "name": "Business Administration", "credits": 90, "duration_years": 3, "university": "Al Akhawayn University", "location": "Ifrane"},
        {"id": 3, "name": "Engineering", "credits": 180, "duration_years": 5, "university": "Hassan II University", "location": "Casablanca"},
        {"id": 4, "name": "Medicine", "credits": 360, "duration_years": 6, "university": "Sidi Mohamed Ben Abdellah University", "location": "Fez"},
        {"id": 5, "name": "Economics", "credits": 100, "duration_years": 3, "university": "Cadi Ayyad University", "location": "Marrakech"},
        {"id": 6, "name": "Literature", "credits": 80, "duration_years": 3, "university": "Mohammed First University", "location": "Oujda"},
        {"id": 7, "name": "Psychology", "credits": 95, "duration_years": 3, "university": "Ibn Tofail University", "location": "Kenitra"},
        {"id": 8, "name": "Architecture", "credits": 200, "duration_years": 5, "university": "National School of Architecture", "location": "Rabat"}
    ],
    
    "student_enrollments": [
        {"id": 1, "user_id": 1, "course_id": 1, "enrollment_date": "2023-09-01", "status": "active", "gpa": 3.8},
        {"id": 2, "user_id": 3, "course_id": 7, "enrollment_date": "2023-09-01", "status": "active", "gpa": 3.6},
        {"id": 3, "user_id": 5, "course_id": 2, "enrollment_date": "2024-01-15", "status": "active", "gpa": 3.9},
        {"id": 4, "user_id": 7, "course_id": 3, "enrollment_date": "2023-09-01", "status": "active", "gpa": 3.7},
        {"id": 5, "user_id": 10, "course_id": 6, "enrollment_date": "2024-09-01", "status": "active", "gpa": 3.5},
        {"id": 6, "user_id": 13, "course_id": 4, "enrollment_date": "2023-09-01", "status": "active", "gpa": 3.4},
        {"id": 7, "user_id": 15, "course_id": 5, "enrollment_date": "2024-02-01", "status": "active", "gpa": 3.8}
    ],
    
    "cities": [
        {"id": 1, "name": "Oujda", "country": "Morocco", "population": 494252, "region": "Oriental", "established": 994},
        {"id": 2, "name": "Casablanca", "country": "Morocco", "population": 3359818, "region": "Casablanca-Settat", "established": 768},
        {"id": 3, "name": "Rabat", "country": "Morocco", "population": 577827, "region": "Rabat-Salé-Kénitra", "established": 1150},
        {"id": 4, "name": "Fez", "country": "Morocco", "population": 1112072, "region": "Fès-Meknès", "established": 789},
        {"id": 5, "name": "Marrakech", "country": "Morocco", "population": 928850, "region": "Marrakech-Safi", "established": 1062},
        {"id": 6, "name": "Tangier", "country": "Morocco", "population": 947952, "region": "Tanger-Tétouan-Al Hoceïma", "established": 682},
        {"id": 7, "name": "Agadir", "country": "Morocco", "population": 421844, "region": "Souss-Massa", "established": 1505},
        {"id": 8, "name": "Meknes", "country": "Morocco", "population": 632079, "region": "Fès-Meknès", "established": 1061},
        {"id": 9, "name": "New York", "country": "USA", "population": 8336817, "region": "New York", "established": 1624},
        {"id": 10, "name": "London", "country": "UK", "population": 9648110, "region": "Greater London", "established": 47}
    ],
    
    "books": [
        {"id": 1, "title": "The Alchemist", "author": "Paulo Coelho", "isbn": "978-0062315007", "pages": 163, "price": 14.99, "genre": "Fiction"},
        {"id": 2, "title": "Sapiens", "author": "Yuval Noah Harari", "isbn": "978-0062316097", "pages": 464, "price": 16.99, "genre": "History"},
        {"id": 3, "title": "Clean Code", "author": "Robert C. Martin", "isbn": "978-0132350884", "pages": 464, "price": 42.99, "genre": "Technology"},
        {"id": 4, "title": "1984", "author": "George Orwell", "isbn": "978-0451524935", "pages": 328, "price": 13.99, "genre": "Fiction"},
        {"id": 5, "title": "Atomic Habits", "author": "James Clear", "isbn": "978-0735211292", "pages": 320, "price": 18.99, "genre": "Self-Help"},
        {"id": 6, "title": "Educated", "author": "Tara Westover", "isbn": "978-0399590504", "pages": 334, "price": 15.99, "genre": "Biography"},
        {"id": 7, "title": "The Lean Startup", "author": "Eric Ries", "isbn": "978-0307887894", "pages": 336, "price": 26.99, "genre": "Business"},
        {"id": 8, "title": "Dune", "author": "Frank Herbert", "isbn": "978-0441172719", "pages": 688, "price": 17.99, "genre": "Science Fiction"},
        {"id": 9, "title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "isbn": "978-0374533557", "pages": 499, "price": 19.99, "genre": "Psychology"},
        {"id": 10, "title": "The Art of War", "author": "Sun Tzu", "isbn": "978-1599869773", "pages": 273, "price": 9.99, "genre": "Philosophy"}
    ],
    
    "events": [
        {"id": 1, "name": "Tech Conference 2024", "date": "2024-03-15", "location": "Casablanca", "attendees": 500, "type": "Conference"},
        {"id": 2, "name": "Startup Pitch Day", "date": "2024-04-10", "location": "Rabat", "attendees": 200, "type": "Networking"},
        {"id": 3, "name": "AI Workshop", "date": "2024-05-20", "location": "Oujda", "attendees": 150, "type": "Workshop"},
        {"id": 4, "name": "Digital Marketing Summit", "date": "2024-06-08", "location": "Marrakech", "attendees": 350, "type": "Summit"},
        {"id": 5, "name": "Cybersecurity Forum", "date": "2024-07-12", "location": "Tangier", "attendees": 280, "type": "Forum"},
        {"id": 6, "name": "Innovation Expo", "date": "2024-08-25", "location": "Fez", "attendees": 600, "type": "Expo"},
        {"id": 7, "name": "Data Science Meetup", "date": "2024-09-14", "location": "Agadir", "attendees": 120, "type": "Meetup"},
        {"id": 8, "name": "Mobile Dev Conference", "date": "2024-10-30", "location": "Meknes", "attendees": 400, "type": "Conference"}
    ],
    
    "transactions": [
        {"id": 1, "user_id": 1, "amount": 1299.99, "type": "purchase", "date": "2024-01-15", "status": "completed", "payment_method": "credit_card"},
        {"id": 2, "user_id": 2, "amount": 179.98, "type": "purchase", "date": "2024-01-18", "status": "completed", "payment_method": "paypal"},
        {"id": 3, "user_id": 3, "amount": 199.99, "type": "purchase", "date": "2024-01-20", "status": "pending", "payment_method": "debit_card"},
        {"id": 4, "user_id": 1, "amount": 59.99, "type": "purchase", "date": "2024-01-22", "status": "completed", "payment_method": "credit_card"},
        {"id": 5, "user_id": 4, "amount": 899.99, "type": "purchase", "date": "2024-01-25", "status": "completed", "payment_method": "bank_transfer"},
        {"id": 6, "user_id": 5, "amount": 119.97, "type": "purchase", "date": "2024-01-28", "status": "completed", "payment_method": "credit_card"},
        {"id": 7, "user_id": 6, "amount": 249.99, "type": "purchase", "date": "2024-02-01", "status": "completed", "payment_method": "paypal"},
        {"id": 8, "user_id": 7, "amount": 259.98, "type": "purchase", "date": "2024-02-03", "status": "processing", "payment_method": "debit_card"},
        {"id": 9, "user_id": 8, "amount": 149.99, "type": "purchase", "date": "2024-02-05", "status": "completed", "payment_method": "credit_card"},
        {"id": 10, "user_id": 9, "amount": 399.99, "type": "purchase", "date": "2024-02-08", "status": "completed", "payment_method": "bank_transfer"},
        {"id": 11, "user_id": 2, "amount": 50.00, "type": "refund", "date": "2024-02-10", "status": "completed", "payment_method": "paypal"},
        {"id": 12, "user_id": 10, "amount": 79.99, "type": "purchase", "date": "2024-02-10", "status": "completed", "payment_method": "credit_card"},
        {"id": 13, "user_id": 11, "amount": 119.99, "type": "purchase", "date": "2024-02-12", "status": "processing", "payment_method": "debit_card"},
        {"id": 14, "user_id": 12, "amount": 139.96, "type": "purchase", "date": "2024-02-15", "status": "completed", "payment_method": "credit_card"},
        {"id": 15, "user_id": 13, "amount": 99.98, "type": "purchase", "date": "2024-02-18", "status": "completed", "payment_method": "paypal"}
    ],
    
    "inventory": [
        {"id": 1, "product_id": 1, "warehouse": "Main Warehouse", "quantity": 45, "location": "A-12-3", "last_updated": "2024-02-20"},
        {"id": 2, "product_id": 2, "warehouse": "Electronics Hub", "quantity": 120, "location": "B-05-7", "last_updated": "2024-02-19"},
        {"id": 3, "product_id": 3, "warehouse": "Home Goods Center", "quantity": 78, "location": "C-08-2", "last_updated": "2024-02-18"},
        {"id": 4, "product_id": 4, "warehouse": "Sports Depot", "quantity": 95, "location": "D-15-1", "last_updated": "2024-02-17"},
        {"id": 5, "product_id": 5, "warehouse": "Electronics Hub", "quantity": 67, "location": "B-12-4", "last_updated": "2024-02-16"},
        {"id": 6, "product_id": 6, "warehouse": "Furniture Storage", "quantity": 34, "location": "F-03-8", "last_updated": "2024-02-15"},
        {"id": 7, "product_id": 7, "warehouse": "Electronics Hub", "quantity": 156, "location": "B-18-6", "last_updated": "2024-02-14"},
        {"id": 8, "product_id": 8, "warehouse": "Sports Depot", "quantity": 89, "location": "D-07-3", "last_updated": "2024-02-13"},
        {"id": 9, "product_id": 9, "warehouse": "Home Goods Center", "quantity": 42, "location": "C-11-5", "last_updated": "2024-02-12"},
        {"id": 10, "product_id": 10, "warehouse": "Electronics Hub", "quantity": 28, "location": "B-20-1", "last_updated": "2024-02-11"}
    ]}
   